# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('alexa_rank', models.IntegerField(blank=True, null=True, verbose_name='Alexa rank')),
                ('date_added', models.DateTimeField(blank=True, null=True, verbose_name='Added')),
                ('date_updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WebsiteCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='webpage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Website'),
        ),
    ]
